### ISSUE TITLE
Use a fixed width on the Objects panel

### ISSUE THREAD

**Issue by gzip** [gmarty/scumm-nes#12]
It's a bit distracting that the Objects panel changes width for every room. Minor problem, simple fix.

**Comment by gmarty** [comment]
This is tricky because the size will vary depending on the room and the language of the ROM.
I don't like it either. The way forward to is to move everything related to the objects to a tab below the room canvas (with `Palette` and `Tilesets`). There's a lot to show and edit (object properties, scripts, initial state...). The list of objects would move there too.

What do you think about that idea?

**Comment by gzip** [comment]
Not sure it will all fit at the bottom, especially when the object info panel is added. I do like the long/tall list for the objects. The rooms panel on the other hand might not need to take up so much room. What do you think about moving the rooms into a select box or small panel above the objects panel so that they're in the same column? Then that gives more width for the objects. I like a select box because it expands to a longer list when you click on it.

**Comment by gzip** [comment]
Currently I have to go look up the room id first if I want to load a specific room. A select box for the rooms would also allow more space to apply some room titles. I have a list of titles available here:
https://github.com/gzip/nes-6502-maniac-mansion-decoded/blob/master/tools/generator/data.js#L24

**Comment by gzip** [comment]
Looks done to me.
