### ISSUE TITLE
Make palettes editable

### ISSUE THREAD

**Issue by gzip** [gmarty/scumm-nes#2]
Data-wise this is probably one of the easiest writes to make, so it could be a good start for allowing edits. It might be fun to roll a nes color picker as well.

**Comment by gmarty** [comment]
Yeah agree. In order to allow edits though there is some work needed: a UI to download the ROM, the ability to edit preivously hacked ROM, some sort of projects management that stores the data locally in case the user presses refresh by mistake...

My approach so far has been to do the edits using the command line. The first experiment was to change the prepositions. See the [code](https://github.com/gmarty/scumm-nes/blob/main/experiments/updatePreps.js). I want to have a more solid edit solution in place before exposing it to the UI.

Happy to hear your opinion if you think both the editing code and the UI should be worked on at the same time!

**Comment by gmarty** [comment]
I landed a first iteration of the colour picker in 7ac6ebd. It doesn't change the ROM yet. It's a purely frontend feature.

**Comment by gzip** [comment]
This is looking great! One minor change. When the first color in any of the 4 palettes is changed, it should be applied to all four palettes automatically since that's how the nes works.

**Comment by gmarty** [comment]
I didn't know that. There's so much I need to learn about the NES. Anyway, this was implemented in 8358b4a.
